AWSTemplateFormatVersion: 2010-09-09

Resources:
  myInstance:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: ami-0096a7a7add65af89
      InstanceType: t2.micro
      KeyName: my-key-pair
      Tags:
        -
          Key: Name
          Value: my-ec2-instance
